<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/GearInvest/GearInvest.csproj" />
    <Compile Include="../shared/*.cs" Link="Shared/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
